<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUwhzsuk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUwhzsuk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUwhzsuk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUwhzsuk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUwhzsuk\appDevDebugProjectContainer([
    'container.build_hash' => 'Uwhzsuk',
    'container.build_id' => '59c68729',
    'container.build_time' => 1701550079,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUwhzsuk');
